#Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
#i 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zestymath
email: zestymathofficial@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Zestymath! Let's learn something together. Please use the e-mail contact to let us know if you find any mistakes, no matter how small. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zestymath.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  zestymath

# Build settings
markdown: kramdown
