#Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
#i 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zestymath
email: contact@zestymath.com
description: "Welcome to Zestymath! Please use the e-mail contact to let me know if you find any mistakes, you feel an explanation could be improved, or you have a suggestion for content. \n"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zestymath.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: zestymath
collections:
    math:
        permalink: /:collection:/:title
    physics:
        permalink: /:collection:/:title
    calculus-I:
        output: true
    calculus-II:
        output: true
    calculus-III:
        output: true
    classical-ft:
        output: true
    cm-I:
        output: true
    cm-II:
        output: true
    cm-III:
        output: true
    cm-IV:
        output: true
    complex-variables:
        output: true
    em-I:
        output: true
    em-II:
        output: true
    em-III:
        output: true
    em-IV:
        output: true
    fm-I:
        output: true
    gr:
        output: true
    greens-functions:
        output: true
    hs-physics-I:
        output: true
    hs-physics-II:
        output: true
    kt:
        output: true
    linear-algebra-I:
        output: true
    linear-algebra-II:
        output: true
    math-methods:
        output: true
    math-cm:
        output: true
    nonlin-dyn-I:
        output: true
    ode-I:
        output: true
    ode-II:
        output: true
    pde-I:
        output: true
    pde-II:
        output: true
    perturb-I:
        output: true
    perturb-II:
        output: true
    physics-I:
        output: true
    physics-II:
        output: true
    qft-I:
        output: true
    qm-I:
        output: true
    qm-II:
        output: true
    qm-III:
        output: true
    qm-IV:
        output: true
    ssp:
        output: true
    td:
        output: true


# Build settings
markdown: kramdown
